apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::979877905152:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-M03GDE94H8AS
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::979877905152:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-20T13:01:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "865"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1a8104ed-e1b1-434b-b651-e4716cddeb61
